#!/usr/bin/env python3
"""Generate link stubs for everything still living in game.asm.

The Android build links the C++ half of Open1560 only - every function that has
not been reimplemented yet is still x86 assembly and cannot come along. This
script turns the linker's own "undefined symbol" list into an assembly file that
defines each one:

  * functions become a tail call to ArtsStubCalled, which logs the symbol name
    and returns 0, so the game keeps running and tells us what it wanted
  * data symbols become zeroed .bss blocks

That gets a linking, launchable binary immediately, and the runtime log becomes
the priority order for real implementations: whatever the game calls first is
what to write first.

Usage:
    python3 gen_stubs.py <link.log> [--out stubs/stubs.S] [--ndk NDK_PATH]
"""

import argparse
import os
import re
import subprocess
import sys

UNDEFINED_RE = re.compile(r'undefined symbol:?\s+(\S+)')

# Slots in a synthesized vtable. The largest class hierarchy here is well under
# this, and the spare entries cost a few hundred bytes.
VTABLE_SLOTS = 64
# Symbol name as it appears in "ld: error: undefined symbol: foo" and friends.


def read_undefined(path):
    symbols = []
    seen = set()

    with open(path, encoding='utf-8', errors='replace') as f:
        for line in f:
            match = UNDEFINED_RE.search(line)

            if not match:
                continue

            symbol = match.group(1).strip().rstrip(':')

            if symbol not in seen:
                seen.add(symbol)
                symbols.append(symbol)

    return symbols


def demangle(symbols, cxxfilt):
    if not symbols:
        return {}

    result = subprocess.run([cxxfilt], input='\n'.join(symbols), capture_output=True, text=True, check=True)

    return dict(zip(symbols, result.stdout.splitlines()))


def is_function(symbol, demangled):
    # Anything with an argument list is a function; so is a plain C name that is
    # not obviously a variable. Data symbols are C++ globals, which demangle
    # unchanged unless they are namespaced.
    if '(' in demangled:
        return True

    if symbol.startswith('_Z'):
        # Mangled but no argument list: a variable, vtable or typeinfo.
        return False

    return False


def emit(symbols, demangled, out_path):
    functions = [s for s in symbols if is_function(s, demangled[s])]
    data = [s for s in symbols if s not in set(functions)]

    # A class whose virtuals all still live in game.asm has no key function in
    # C++, so no translation unit emits its vtable. Left as a zeroed block, every
    # virtual call through it jumps to address zero. Instead each slot points at
    # ArtsVirtualStub, which logs its caller and returns 0 - the same deal as the
    # function stubs.
    vtables = [s for s in data if s.startswith('_ZTV')]
    data = [s for s in data if not s.startswith('_ZTV')]

    lines = [
        '// Generated by android/gen_stubs.py - do not edit.',
        '//',
        '// One entry per symbol still defined in game.asm. Functions tail-call',
        '// ArtsStubCalled with their name (it logs and returns 0); data symbols are',
        '// zeroed blocks. Regenerate after every link attempt.',
        '',
    ]

    # Each architecture needs its own way to pass the name and tail call.
    arches = [
        ('__aarch64__', lambda symbol, index: [
            f'    adrp x0, .Lstub_name_{index}',
            f'    add x0, x0, :lo12:.Lstub_name_{index}',
            '    b ArtsStubCalled',
        ]),
        ('__x86_64__', lambda symbol, index: [
            f'    leaq .Lstub_name_{index}(%rip), %rdi',
            '    jmp ArtsStubCalled',
        ]),
    ]

    for arch, emit_body in arches:
        lines += [f'#if defined({arch})', '', '    .text', '']

        for index, symbol in enumerate(functions):
            lines += [
                f'    // {demangled[symbol]}',
                f'    .global {symbol}',
                f'    .type {symbol}, %function',
                f'{symbol}:',
            ]
            lines += emit_body(symbol, index)
            lines += [f'    .size {symbol}, . - {symbol}', '']

        lines += ['    .section .rodata', '']

        for index, symbol in enumerate(functions):
            text = demangled[symbol].replace('"', "'")
            lines += [f'.Lstub_name_{index}:', f'    .asciz "{text}"', '']

        lines += ['    .section .data.rel.ro', '']

        for symbol in vtables:
            lines += [
                f'    // {demangled[symbol]}',
                f'    .global {symbol}',
                f'    .type {symbol}, %object',
                '    .p2align 3',
                f'{symbol}:',
                '    .quad 0    // offset to top',
                '    .quad 0    // typeinfo',
                f'    .rept {VTABLE_SLOTS}',
                '    .quad ArtsVirtualStub',
                '    .endr',
                f'    .size {symbol}, . - {symbol}',
                '',
            ]

        lines += ['    .bss', '']

        for symbol in data:
            lines += [
                f'    // {demangled[symbol]}',
                f'    .global {symbol}',
                f'    .type {symbol}, %object',
                f'    .comm {symbol}, 4096, 16',
                '',
            ]

        lines += ['#endif', '']

    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    with open(out_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    return functions, data, vtables


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('link_log')
    parser.add_argument('--out', default=os.path.join(os.path.dirname(__file__), 'stubs', 'stubs.S'))
    parser.add_argument('--ndk', default=os.environ.get('NDK', os.path.expanduser('~/android/android-ndk-r27c')))
    args = parser.parse_args()

    cxxfilt = os.path.join(args.ndk, 'toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-cxxfilt')

    symbols = read_undefined(args.link_log)

    if not symbols:
        print('No undefined symbols in', args.link_log)
        return 0

    demangled = demangle(symbols, cxxfilt)
    functions, data, vtables = emit(symbols, demangled, args.out)

    print(f'{len(symbols)} undefined symbols -> {args.out}')
    print(f'  functions: {len(functions)}')
    print(f'  vtables  : {len(vtables)}')
    print(f'  data     : {len(data)}')

    return 0


if __name__ == '__main__':
    sys.exit(main())
